FROM jenkins/jenkins@sha256:f4f65e6cd1405cd889b7f5ac33f9d5cdc2a099de6b87fe8a3933b9c5d53d1d02

USER root
RUN apt-get update && apt-get install -y \
    python3 \
    ssh \
    openssh-client \
    ansible \
    && rm -rf /var/lib/apt/lists/*

USER jenkins
